server:
  port: 8088

mybatis:
  mapper-locations: classpath:mapper/*.xml #对应你的mapper.xml映射文件
  type-aliases-package: com.springboot.Entity #对应实体类
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/llbAndyxb
    driver-class-name: com.mysql.jdbc.Driver
    data-username: root
    password: system
