
mybatis:
  mapper-locations: classpath:mapper/*.xml #对应你的mapper.xml映射文件
  type-aliases-package: com.springboot.Entity #对应实体类

spring:
  datasource:
    url: jdbc:mysql://47.100.162.55:3306/LosSantosPlanDB?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: ehow
    password: LosSantosPlan
    driver-class-name: com.mysql.cj.jdbc.Driver